[project]
name = "adownloader-rich"
version = "0.1.0"
description = "Python Async File Downloader"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.11.18",
    "rich>=14.0.0",
    "rich-argparse>=1.7.0",
]

[project.scripts]
adownloader = "adownloader"